import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import ImageUploader from '../components/inputrPreview/index';
import { useState } from 'react';
import axios from 'axios';

const Home: NextPage = () => {

  const[image1, setImage1] = useState<File>();
  const[image2, setImage2] = useState<File>();
  const[similarity, setSimilarity] = useState<number>();

  const imageHandle1 = (image: File) => {
    setImage1(image);
  };

  const imageHandle2 = (image: File) => {
    setImage2(image);
  };

  function fileToBase64(file: File): Promise<string> {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = () => {
        const result = reader.result?.toString();
        if (!result) {
          reject(new Error("Failed to convert file to base64."));
        }
        resolve(result!.split(",")[1]); // Remove data URL prefix
      };
      reader.onerror = (error) => reject(error);
    });
  }

  const upload = async (image1: File | undefined, image2: File | undefined): Promise<string> => {
    

    if(!image1 || !image2) return "";


    const originalImage = await fileToBase64(image1);
    const compareImage = await fileToBase64(image2);

    const response = await axios.post(
      "https://rxbkzlxtuh.execute-api.us-east-1.amazonaws.com/face2face/",
      {
        originalImage:originalImage,
        compareImage:compareImage
      }
     
    );

    console.log(response);
    if (response.data.FaceMatches && response.data.FaceMatches[0]) {
      setSimilarity(response.data.FaceMatches[0].Similarity);
    }
    else {
      setSimilarity(0)
    }
    return response.data;
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Face2Face</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <img src="favicon.ico" style={{width: "250px"}}></img>
        <h1 className={styles.title}>
          Face<a href="https://github.com/ayanfaustt/p4_project">2</a>Face
        </h1>
        
        <p className={styles.description}>
          Comparador de Faces
        </p>

        <div className={styles.grid} style={{paddingLeft: "130px"}}>
          <div>
            <ImageUploader onChange={imageHandle1}></ImageUploader>
          </div>
          <div>
            <ImageUploader onChange={imageHandle2}></ImageUploader>
          </div>
        </div>
        <div style={{paddingTop: "50px"}}>
          <button onClick={() => upload(image1, image2)}>Comparar!</button>
        </div>

      <span style={{paddingTop: "20px"}}>
        Taxa de similaridade de {similarity} %
      </span>

      </main>

    </div>
  )
}

export default Home
